### ISSUE TITLE
fork for django-templatag_sugar

### ISSUE THREAD

**Issue by ghost** [django-rdf-tools/django-coop#123]
La mise en place d'un virtualenv pour une coop est cassée, car le fork sur git+git://github.com/jonasgeiregat/django-templatetag-sugar.git ne fonctionne plus le répertoire n'existe plus.

**Comment by domguard** [comment]
OK nouveau fork dispo sur https://github.com/quinode/django-templatetag-sugar
j'ai modifié requirements.txt dans coop-template
par contre si tu as intégré le template projet a django-coop faudrait pusher ça...

**Comment by ghost** [comment]
C'est fait, mais dans la branche dynamic_loading

Le 09/08/2012 13:13, domguard a écrit :

> OK nouveau fork dispo sur 
> https://github.com/quinode/django-templatetag-sugar
> j'ai modifié coop-template
> par contre si tu as intégré le template projet a django-coop faudrait 
> pusher ça...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/quinode/django-coop/issues/123#issuecomment-7611381.

## 

Claude Huchet  -- Coopérative Quinode
