### ISSUE TITLE
impossible de mettre à jour une coop existante sur la branche dynamic_loading

### ISSUE THREAD

**Issue by ghost** [django-rdf-tools/django-coop#124]
Bon ce n'est peut être pas une vraie issue... 
Je me sers d'une base de données qui fonctionnait sur la branche master.

Je me suis placée dans un environnent construit avec la banche dynamic_loading de django-coop et integration de coop-tag (django1.4 version officiel pour contourner l'issue #122)
Dans ma bd, j'ai renommé les tables`coop_tag_ctag` et `coop_tag_ctaggeditem` en `coop_local_tag` et `coop_local_taggeditem`,  j'ai fait la migration south (`schemamigration coop_local --initial` puis `migrate coop_local --fake`, qui me dit qu'il n'y a rien à migrer)

<pre>
Running migrations for coop_local:
- Nothing to migrate.
 - Loading initial data for coop_local.
Installed 0 object(s) from 0 fixture(s)
</pre>

Par contre, il m'en manque un peu....

<pre>
DatabaseError: ERREUR:  la colonne coop_local_tag.parent_id n'existe pas
LINE 1: ..."coop_local_tag"."name", "coop_local_tag"."slug", "coop_loca...
</pre>

Le message est cohérent.... la table ne contient pas le champ `parent_id` alors que la migration contient elle un champ `parent`. 
Bien sur si on construit une nouvelle applie coop, le syncdb construit un champ `parent_id` dans la table `coop_local_tag`

C'est peut être moi qui ai oublié un truc. En tout cas, difficile d'aller plus loin

**Comment by domguard** [comment]
il faut que tu relance :

./manage.py migrate coop_local --auto

là il verra que son modèle coop_local_tag différe de celui de la BD et complétera

**Comment by ghost** [comment]
J'avais bien essayé (et un peu oublié de l'expliquer), mais

<pre>
(dj4c)clo@thinkpad:~/projects/test/aapeas$ ./manage.py schemamigration coop_local --auto 
/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/conf/__init__.py:75: DeprecationWarning: The ADMIN_MEDIA_PREFIX setting has been removed; use STATIC_URL instead.
  "use STATIC_URL instead.", DeprecationWarning)
*** VANILLA COOP MODELS : LinkProperty, Link, Article, Tag, TaggedItem, Calendar, Dated, Event, EventCategory, Occurrence, Person, PersonCategory, Contact, Engagement, Role, RoleCategory, Relation, OrganizationCategory, Organization, ExchangeMethod, Product, Exchange, MailingList, Subscription
*** CUSTOMIZED COOP MODELS : 
*** ADDITIONAL MODELS : 
Nothing seems to have changed.
</pre>


Soit South est un peu perturbé par le "dynamic loading", soit il me manque quelque chose pour me retrouver dans un état cohérent. J'ai constaté le problème uniquement sur les tags. D'autres models ont-ils bougé?
