### ISSUE TITLE
Problème d'install GeoDjango sous Windows

### ISSUE THREAD

**Issue by django-rdf-tools** [django-rdf-tools/django-coop#23]
Sur mon poste de dev avec un Windows (oui je sais mais on choisit pas toujours dans la vie :) )

Si je mets 'coop_geo' dans les INSTALL_APPS, j'ai l'erreur suivante:

ImportError: Could not find the GEOS library (tried "geos_c", "libgeos_c-1"). Try setting GEOS_LIBRARY_PATH in your settings.

J'ai suivi la doc GeoDjango et essayé d'installer OsGeo4W http://download.osgeo.org/osgeo4w/osgeo4w-setup.exe sans être très sur si c'est nécessaire ou pas.

Pas hyper urgent puisque je peux le désactiver dans mon local_settings et que j'en ai pas besoin pour l'instant.

Un peu d'aide serait le bienvenue et m'éviterait de passer par une VM (ou d'anticiper un peu l'achat d'une nouvelle machine).

merci
luc

**Comment by domguard** [comment]
Oui Luc

PostGIS et compagnie peuvent être galère à installer sous Windows
C'est un peu comme les librairies librdf, ça marche beaucoup mieux en natif sous Linux...
et c'est souvent simple comme "apt-get install"

J'ai vécu la galère l'an dernier en testant GeoDjango sur Mac, avec des tas de bouts d'installs alternatifs, de tutoriaux contradictoires, etc 
donc là, pour pouvoir accéder au boulot d'Etienne j'ai pris le temps de faire un script d'install qui servira pour installer des instances de l'application de base, mais surtout pour l'instant pour avoir un serveur Linux fonctionnel qui réplique le serveur .

Tout est détaillé sur le wiki : https://github.com/quinode/django-coop/wiki/Script-Fabric
